/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BenchmarkRouteImport } from './routes/benchmark'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as PilotRouteImport } from './routes/pilot'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TokenizerRouteImport } from './routes/tokenizer'
import { Route as ReceiptIdRouteImport } from './routes/receipt.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarkRoute = BenchmarkRouteImport.update({
  id: '/benchmark',
  path: '/benchmark',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const PilotRoute = PilotRouteImport.update({
  id: '/pilot',
  path: '/pilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenizerRoute = TokenizerRouteImport.update({
  id: '/tokenizer',
  path: '/tokenizer',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptIdRoute = ReceiptIdRouteImport.update({
  id: '/receipt/$id',
  path: '/receipt/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/tokenizer': typeof TokenizerRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/tokenizer': typeof TokenizerRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmark': typeof BenchmarkRoute
  '/connect': typeof ConnectRoute
  '/demo': typeof DemoRoute
  '/pilot': typeof PilotRoute
  '/research': typeof ResearchRoute
  '/results': typeof ResultsRoute
  '/roadmap': typeof RoadmapRoute
  '/team': typeof TeamRoute
  '/tokenizer': typeof TokenizerRoute
  '/receipt/$id': typeof ReceiptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmark'
    | '/connect'
    | '/demo'
    | '/pilot'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/team'
    | '/tokenizer'
    | '/receipt/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmark'
    | '/connect'
    | '/demo'
    | '/pilot'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/team'
    | '/tokenizer'
    | '/receipt/$id'
  id:
    | '__root__'
    | '/'
    | '/benchmark'
    | '/connect'
    | '/demo'
    | '/pilot'
    | '/research'
    | '/results'
    | '/roadmap'
    | '/team'
    | '/tokenizer'
    | '/receipt/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarkRoute: typeof BenchmarkRoute
  ConnectRoute: typeof ConnectRoute
  DemoRoute: typeof DemoRoute
  PilotRoute: typeof PilotRoute
  ResearchRoute: typeof ResearchRoute
  ResultsRoute: typeof ResultsRoute
  RoadmapRoute: typeof RoadmapRoute
  TeamRoute: typeof TeamRoute
  TokenizerRoute: typeof TokenizerRoute
  ReceiptIdRoute: typeof ReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmark': {
      id: '/benchmark'
      path: '/benchmark'
      fullPath: '/benchmark'
      preLoaderRoute: typeof BenchmarkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pilot': {
      id: '/pilot'
      path: '/pilot'
      fullPath: '/pilot'
      preLoaderRoute: typeof PilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokenizer': {
      id: '/tokenizer'
      path: '/tokenizer'
      fullPath: '/tokenizer'
      preLoaderRoute: typeof TokenizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipt/$id': {
      id: '/receipt/$id'
      path: '/receipt/$id'
      fullPath: '/receipt/$id'
      preLoaderRoute: typeof ReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarkRoute: BenchmarkRoute,
  ConnectRoute: ConnectRoute,
  DemoRoute: DemoRoute,
  PilotRoute: PilotRoute,
  ResearchRoute: ResearchRoute,
  ResultsRoute: ResultsRoute,
  RoadmapRoute: RoadmapRoute,
  TeamRoute: TeamRoute,
  TokenizerRoute: TokenizerRoute,
  ReceiptIdRoute: ReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
